import { Inter, Bruno_Ace } from "next/font/google";

import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const brunoAce = Bruno_Ace({
  weight: "400",
  variable: "--font-bruno-ace",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#14131a]`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
